void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int _putchar(char c);
int factorial(int n);
int find_sqrt(int n, int i);
int check_prime(int n, int i);
int tmp_prime(int n, int i);
int _strlen_recursion(char *s);
int check_palindrome(char *s, int i, int j);
